apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authenticator.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ include "authenticator.componentName" . }}
  template:
    metadata:
      labels:
        component: {{ include "authenticator.componentName" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: d0rka/users-authenticator
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: BACKEND_HOST
              value: {{ .Values.backendHost }}
            - name: BACKEND_PORT
              value: "{{ .Values.backendPort }}"
            - name: OKTA_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: oktaclientid
                  key: OKTA_CLIENTID
            - name: OKTA_ISSUER
              valueFrom:
                secretKeyRef:
                  name: oktaissuer
                  key: OKTA_ISSUER
