apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterIpServiceName }}
  labels:
    {{- include "authenticator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: {{ .Values.containerPort }}
  selector:
    component: {{ include "authenticator.componentName" . }}
