# Default values for folder-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# Do not change or override these
baseBackendImage: d0rka/folder-service-backend
baseFrontendImage: d0rka/folder-service-frontend

# This is the docker image version number
applicationVersion: 0.2.0

resources: {}
