apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-backend-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: authentication-service-backend-proxy-server
  template:
    metadata:
      labels:
        component: authentication-service-backend-proxy-server
    spec:
      containers:
        - name: authentication-service-backend-proxy
          image: d0rka/authentication-service-backend-proxy
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_HOST
              value: {{ .Values.backendHost }}
            - name: BACKEND_PORT
              value: "{{ .Values.backendPort }}"
            - name: OKTA_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: oktaclientid
                  key: OKTA_CLIENTID
            - name: OKTA_ISSUER
              valueFrom:
                secretKeyRef:
                  name: oktaissuer
                  key: OKTA_ISSUER
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: authentication-service-frontend-web
  template:
    metadata:
      labels:
        component: authentication-service-frontend-web
    spec:
      containers:
        - name: authentication-service-frontend
          image: d0rka/authentication-service-frontend
          ports:
            - containerPort: 3001
          env:
            - name: OKTA_CLIENTID
              valueFrom:
                secretKeyRef:
                  name: oktaclientid
                  key: OKTA_CLIENTID
            - name: OKTA_ISSUER
              valueFrom:
                secretKeyRef:
                  name: oktaissuer
                  key: OKTA_ISSUER
