apiVersion: v1
kind: Service
metadata:
  name: authentication-service-backend-proxy-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: authentication-service-backend-proxy-server
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-frontend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: authentication-service-frontend-web
  ports:
    -
      port: 3001
      targetPort: 3001
